### PR TITLE
Added seeding functionality (untested)

### PR DESCRIPTION
**Pull request by polarise**
It would be nice to be able re-run by simply specifying a known seed.

P

### CODE REVIEW

**Comment by esanzgar** [comment]
I don't see how you are using the seed (random.seed([x]))

According to the documentation, the default seed comes from the operating system if available, otherwise it uses the time:
https://docs.python.org/2/library/random.html#random.seed

**Comment by polarise** [comment]
You are right! I forgot to seed the RNG. Let me to that then issue another PR.

**Comment by polarise** [comment]
Could you please try it now? I hope that corrects my omission.

**Comment by esanzgar** [comment]
Yes, it looks better.

However, the fundamental question still remains: what algorithm will you use to generate the seed? Will you do better than the operating system (currently the scripts uses the default os.urandom())?

It is not a critic, just a comment.

**Comment by polarise** [comment]
Oh no! The point is not to come up with a better seed. I guess you're still following up from my comments. I don't doubt that the RNG is random. I think I was just lucky to be selected to have the same team mate too often. This PR is just a means to ensure accountability: we can always re-run the script using the same seed to get the same results. I'm just proposing an improvement to your script! ;-)

**Pull request merged**
